version: '3.7'

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/data/postgres
    networks:
      - ignite

  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/rentx/app
    depends_on: 
      - database_ignite
    networks:
      - ignite

volumes:
  pgdata:

networks:
  ignite:
    driver: "bridge"