version: '3.7'

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/data/postgres

  # app:
  #   build: .
  #   container_name: rentx
  #   restart: always
  #   ports: 
  #     - 3333:3333
  #     - 9229:9229
  #   volumes: 
  #     - .:/rentx/app
  #   links: 
  #     - database_ignite
  #   depends_on:
  #     - database_ignite

volumes:
  pgdata:
